/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrainDumpRouteImport } from './routes/brain-dump'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainDumpRoute = BrainDumpRouteImport.update({
  id: '/brain-dump',
  path: '/brain-dump',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain-dump': typeof BrainDumpRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRoute
  '/reflect': typeof ReflectRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain-dump': typeof BrainDumpRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRoute
  '/reflect': typeof ReflectRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brain-dump': typeof BrainDumpRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRoute
  '/reflect': typeof ReflectRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain-dump'
    | '/dashboard'
    | '/decide'
    | '/goals'
    | '/login'
    | '/matrix'
    | '/reflect'
    | '/settings'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain-dump'
    | '/dashboard'
    | '/decide'
    | '/goals'
    | '/login'
    | '/matrix'
    | '/reflect'
    | '/settings'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/brain-dump'
    | '/dashboard'
    | '/decide'
    | '/goals'
    | '/login'
    | '/matrix'
    | '/reflect'
    | '/settings'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainDumpRoute: typeof BrainDumpRoute
  DashboardRoute: typeof DashboardRoute
  DecideRoute: typeof DecideRoute
  GoalsRoute: typeof GoalsRoute
  LoginRoute: typeof LoginRoute
  MatrixRoute: typeof MatrixRoute
  ReflectRoute: typeof ReflectRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain-dump': {
      id: '/brain-dump'
      path: '/brain-dump'
      fullPath: '/brain-dump'
      preLoaderRoute: typeof BrainDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainDumpRoute: BrainDumpRoute,
  DashboardRoute: DashboardRoute,
  DecideRoute: DecideRoute,
  GoalsRoute: GoalsRoute,
  LoginRoute: LoginRoute,
  MatrixRoute: MatrixRoute,
  ReflectRoute: ReflectRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
